# Generated by Django 2.2.4 on 2020-02-24 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200224_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='Reviews',
            new_name='reviews',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='Username',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='Rating',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='Title',
        ),
        migrations.AddField(
            model_name='reviews',
            name='posted_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
