# Generated by Django 2.2.4 on 2020-02-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_reviews_game_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='game_title',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='image',
        ),
        migrations.AddField(
            model_name='reviews',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
