# Generated by Django 2.2.4 on 2020-02-27 11:58

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200227_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=users.models.IntegerRangeField(null=True),
        ),
    ]
