# Generated by Django 2.2.4 on 2020-06-18 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200227_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Games'),
        ),
    ]
