# Generated by Django 2.2.4 on 2020-06-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200618_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
