# Generated by Django 2.2.4 on 2020-06-18 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200618_0336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
