# Generated by Django 2.2.4 on 2020-06-18 04:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
import reviews.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('rating', reviews.models.IntegerRangeField(null=True)),
                ('reviews', models.TextField()),
                ('posted_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Games')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
