# Generated by Django 2.2.4 on 2020-02-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_games_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
