# Generated by Django 2.2.4 on 2020-02-13 15:37

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=pyuploadcare.dj.models.ImageField(null=True),
        ),
    ]
