# Generated by Django 2.2.4 on 2020-02-28 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200228_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='cost',
        ),
    ]
