# Generated by Django 2.2.4 on 2020-02-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_games_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
