# Generated by Django 2.2.4 on 2020-02-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20200228_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='cost',
        ),
    ]
